/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EarlyPredictionRouteImport } from './routes/early-prediction'
import { Route as PmuEventDataRouteImport } from './routes/pmu-event-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyPredictionRoute = EarlyPredictionRouteImport.update({
  id: '/early-prediction',
  path: '/early-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const PmuEventDataRoute = PmuEventDataRouteImport.update({
  id: '/pmu-event-data',
  path: '/pmu-event-data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/early-prediction': typeof EarlyPredictionRoute
  '/pmu-event-data': typeof PmuEventDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/early-prediction': typeof EarlyPredictionRoute
  '/pmu-event-data': typeof PmuEventDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/early-prediction': typeof EarlyPredictionRoute
  '/pmu-event-data': typeof PmuEventDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/early-prediction' | '/pmu-event-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/early-prediction' | '/pmu-event-data'
  id: '__root__' | '/' | '/early-prediction' | '/pmu-event-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarlyPredictionRoute: typeof EarlyPredictionRoute
  PmuEventDataRoute: typeof PmuEventDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-prediction': {
      id: '/early-prediction'
      path: '/early-prediction'
      fullPath: '/early-prediction'
      preLoaderRoute: typeof EarlyPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmu-event-data': {
      id: '/pmu-event-data'
      path: '/pmu-event-data'
      fullPath: '/pmu-event-data'
      preLoaderRoute: typeof PmuEventDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarlyPredictionRoute: EarlyPredictionRoute,
  PmuEventDataRoute: PmuEventDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
